# Generated by Django 5.1.5 on 2025-06-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comforecast',
            name='pid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cross Ref'),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='pid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cross Ref'),
        ),
        migrations.AddField(
            model_name='storeforecast',
            name='pid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cross Ref'),
        ),
    ]
