# Generated by Django 5.1.5 on 2025-06-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetail',
            old_name='last_project_review_date',
            new_name='last_projection_review_date',
        ),
        migrations.RenameField(
            model_name='productdetail',
            old_name='blu',
            new_name='rlj',
        ),
        migrations.AddField(
            model_name='comforecast',
            name='product_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cross Ref'),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='product_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cross Ref'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='external_factor_percentage',
            field=models.FloatField(blank=True, null=True, verbose_name='External Factor Percentage'),
        ),
        migrations.AddField(
            model_name='sheetupload',
            name='categories',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sheetupload',
            name='final_quantity_report',
            field=models.FileField(blank=True, null=True, upload_to='final_quantity_report/', verbose_name='Final Quantity Report'),
        ),
        migrations.AddField(
            model_name='sheetupload',
            name='month_from',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sheetupload',
            name='month_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sheetupload',
            name='output_folder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sheetupload',
            name='percentage',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sheetupload',
            name='summary',
            field=models.FileField(blank=True, null=True, upload_to='summary/', verbose_name='Summary File'),
        ),
        migrations.AddField(
            model_name='storeforecast',
            name='product_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cross Ref'),
        ),
    ]
