# Generated by Django 5.1.5 on 2025-06-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='forecast_month_week',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='selected_months',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
