# Generated by Django 5.1.5 on 2025-06-18 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_productdetail_forecast_month_week_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='forecastnote',
            index=models.Index(fields=['productdetail'], name='forecast_fo_product_ae4857_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastnote',
            index=models.Index(fields=['sheet'], name='forecast_fo_sheet_i_efe0c6_idx'),
        ),
        migrations.AddIndex(
            model_name='forecastnote',
            index=models.Index(fields=['created_at'], name='forecast_fo_created_09072d_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyforecast',
            index=models.Index(fields=['productdetail'], name='forecast_mo_product_00d5a9_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyforecast',
            index=models.Index(fields=['sheet'], name='forecast_mo_sheet_i_717985_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyforecast',
            index=models.Index(fields=['variable_name', 'year'], name='forecast_mo_variabl_977154_idx'),
        ),
        migrations.AddIndex(
            model_name='productdetail',
            index=models.Index(fields=['sheet'], name='forecast_pr_sheet_i_1b504a_idx'),
        ),
        migrations.AddIndex(
            model_name='productdetail',
            index=models.Index(fields=['product_type'], name='forecast_pr_product_6d0ae5_idx'),
        ),
        migrations.AddIndex(
            model_name='productdetail',
            index=models.Index(fields=['category'], name='forecast_pr_categor_76db72_idx'),
        ),
        migrations.AddIndex(
            model_name='productdetail',
            index=models.Index(fields=['birthstone'], name='forecast_pr_birthst_b6a06c_idx'),
        ),
        migrations.AddIndex(
            model_name='productdetail',
            index=models.Index(fields=['assigned_to'], name='forecast_pr_assigne_656b40_idx'),
        ),
        migrations.AddIndex(
            model_name='productdetail',
            index=models.Index(fields=['product_id'], name='forecast_pr_product_7cdfc2_idx'),
        ),
        migrations.AddIndex(
            model_name='productdetail',
            index=models.Index(fields=['status'], name='forecast_pr_status_ad39d2_idx'),
        ),
        migrations.AddIndex(
            model_name='productdetail',
            index=models.Index(fields=['forecast_month'], name='forecast_pr_forecas_07b57d_idx'),
        ),
        migrations.AddIndex(
            model_name='productdetail',
            index=models.Index(fields=['is_red_box_item'], name='forecast_pr_is_red__da4690_idx'),
        ),
        migrations.AddIndex(
            model_name='productdetail',
            index=models.Index(fields=['is_considered_birthstone'], name='forecast_pr_is_cons_048e1e_idx'),
        ),
        migrations.AddIndex(
            model_name='productdetail',
            index=models.Index(fields=['is_added_quantity_using_macys_soq'], name='forecast_pr_is_adde_ba2c56_idx'),
        ),
        migrations.AddIndex(
            model_name='productdetail',
            index=models.Index(fields=['is_added_only_to_balance_macys_soq'], name='forecast_pr_is_adde_aa743b_idx'),
        ),
        migrations.AddIndex(
            model_name='productdetail',
            index=models.Index(fields=['is_below_min_order'], name='forecast_pr_is_belo_16d89f_idx'),
        ),
        migrations.AddIndex(
            model_name='productdetail',
            index=models.Index(fields=['is_over_macys_soq'], name='forecast_pr_is_over_4aa637_idx'),
        ),
        migrations.AddIndex(
            model_name='productdetail',
            index=models.Index(fields=['is_need_to_review_first'], name='forecast_pr_is_need_a89b82_idx'),
        ),
        migrations.AddIndex(
            model_name='productdetail',
            index=models.Index(fields=['valentine_day'], name='forecast_pr_valenti_8ecfb5_idx'),
        ),
        migrations.AddIndex(
            model_name='productdetail',
            index=models.Index(fields=['mothers_day'], name='forecast_pr_mothers_f38e68_idx'),
        ),
        migrations.AddIndex(
            model_name='productdetail',
            index=models.Index(fields=['fathers_day'], name='forecast_pr_fathers_f0eb2a_idx'),
        ),
        migrations.AddIndex(
            model_name='productdetail',
            index=models.Index(fields=['mens_day'], name='forecast_pr_mens_da_c76ebf_idx'),
        ),
        migrations.AddIndex(
            model_name='productdetail',
            index=models.Index(fields=['womens_day'], name='forecast_pr_womens__905d73_idx'),
        ),
        migrations.AddIndex(
            model_name='sheetupload',
            index=models.Index(fields=['user'], name='forecast_sh_user_id_f0fbc1_idx'),
        ),
        migrations.AddIndex(
            model_name='sheetupload',
            index=models.Index(fields=['uploaded_at'], name='forecast_sh_uploade_106365_idx'),
        ),
    ]
