# Generated by Django 5.1.5 on 2025-06-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_comforecast_pid_omniforecast_pid_storeforecast_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetupload',
            name='summary',
            field=models.FileField(blank=True, null=True, upload_to='summary/', verbose_name='Summary File'),
        ),
    ]
