# Generated by Django 5.1.5 on 2025-06-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0003_sheetupload_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetupload',
            name='categories',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sheetupload',
            name='month_from',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sheetupload',
            name='month_to',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sheetupload',
            name='output_folder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sheetupload',
            name='percentage',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
