# Generated by Django 5.1.5 on 2025-06-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0003_forecastnote_forecast_fo_product_ae4857_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetail',
            old_name='current_fc_index',
            new_name='current_fc_index_original',
        ),
        migrations.RenameField(
            model_name='productdetail',
            old_name='forecasting_method',
            new_name='forecasting_method_original',
        ),
        migrations.RenameField(
            model_name='productdetail',
            old_name='rolling_method',
            new_name='rolling_method_original',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='updated_12_month_fc_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='updated_current_fc_index',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='updated_forecasting_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='updated_rolling_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='updated_std_trend',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='std_index_value_original',
            field=models.FloatField(blank=True, null=True, verbose_name='STD Index Value'),
        ),
    ]
