# Generated by Django 5.1.5 on 2025-06-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0004_sheetupload_categories_sheetupload_month_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='external_factor_percentage',
            field=models.FloatField(blank=True, null=True, verbose_name='External Factor Percentage'),
        ),
    ]
