# Generated by Django 5.1.5 on 2025-06-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0005_productdetail_external_factor_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetupload',
            name='final_quantity_report',
            field=models.FileField(blank=True, null=True, upload_to='final_quantity_report/', verbose_name='Final Quantity Report'),
        ),
    ]
