# Generated by Django 5.1.5 on 2025-06-11 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0006_sheetupload_final_quantity_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetail',
            old_name='last_project_review_date',
            new_name='last_projection_review_date',
        ),
        migrations.RenameField(
            model_name='productdetail',
            old_name='blu',
            new_name='rlj',
        ),
    ]
