# Generated by Django 5.1.5 on 2025-06-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0007_rename_last_project_review_date_productdetail_last_projection_review_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comforecast',
            old_name='pid',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='omniforecast',
            old_name='pid',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='storeforecast',
            old_name='pid',
            new_name='product_id',
        ),
    ]
