# Generated by Django 5.1.5 on 2025-06-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0007_rename_last_project_review_date_productdetail_last_projection_review_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comforecast',
            old_name='month_12_fc_index_for_com_sales',
            new_name='com_trend_for_selected_month',
        ),
        migrations.RenameField(
            model_name='comforecast',
            old_name='trend_of_com_sales_for_selected_month',
            new_name='final_com_trend',
        ),
        migrations.RenameField(
            model_name='comforecast',
            old_name='is_inventory_maintained_com_sales',
            new_name='is_com_inventory_maintained',
        ),
        migrations.RenameField(
            model_name='comforecast',
            old_name='pid',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='comforecast',
            old_name='trend_of_total_sales',
            new_name='std_index_value',
        ),
        migrations.RenameField(
            model_name='omniforecast',
            old_name='com_trend',
            new_name='average_eoh_oh',
        ),
        migrations.RenameField(
            model_name='omniforecast',
            old_name='store_month_12_fc_index',
            new_name='com_trend_for_selected_month',
        ),
        migrations.RenameField(
            model_name='omniforecast',
            old_name='pid',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='productdetail',
            old_name='algorithm_generated_final_quantity',
            new_name='forecast_month_planned_oh_before',
        ),
        migrations.RenameField(
            model_name='productdetail',
            old_name='forecasting_method_original',
            new_name='forecasting_method',
        ),
        migrations.RenameField(
            model_name='productdetail',
            old_name='is_lead_guideline_holiday',
            new_name='is_lead_guideline_in_holiday',
        ),
        migrations.RenameField(
            model_name='productdetail',
            old_name='forecast_month_planned_oh',
            new_name='lead_time_old',
        ),
        migrations.RenameField(
            model_name='productdetail',
            old_name='macys_soq',
            new_name='macys_proj_receipt_upto_forecast_month',
        ),
        migrations.RenameField(
            model_name='productdetail',
            old_name='next_forecast_month_planned_oh',
            new_name='next_forecast_month_planned_oh_before',
        ),
        migrations.RenameField(
            model_name='storeforecast',
            old_name='new_trend',
            new_name='average_eoh_oh',
        ),
        migrations.RenameField(
            model_name='storeforecast',
            old_name='pid',
            new_name='product_id',
        ),
        migrations.AddField(
            model_name='comforecast',
            name='is_handle_large_trend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comforecast',
            name='trend_index_difference',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comforecast',
            name='ty_com_sales_unit_selected_month_sum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='final_com_trend',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='forecast_month_required_quantity_com',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='forecast_month_required_quantity_store',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='is_handle_large_trend_com',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='is_handle_large_trend_store',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='is_reduced_loss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='loss_updated',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='ly_com_sales_unit_slected_month_sum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='ly_store_sales_unit_slected_month_sum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='next_forecast_month_required_quantity_com',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='next_forecast_month_required_quantity_store',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='std_index_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='store_month_12_fc_index_original',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='ty_com_sales_unit_slected_month_sum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='ty_store_sales_unit_slected_month_sum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='current_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='forecast_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='forecast_date_old',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='recommended_total_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeforecast',
            name='is_handle_large_trend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeforecast',
            name='is_reduced_loss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeforecast',
            name='loss_updated',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeforecast',
            name='ly_unit_sales_new_trend',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeforecast',
            name='std_index_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeforecast',
            name='std_trend',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeforecast',
            name='std_ty_unit_Sales_std',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeforecast',
            name='ty_unit_sales_new_trend',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
