# Generated by Django 5.1.5 on 2025-06-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0008_rename_month_12_fc_index_for_com_sales_comforecast_com_trend_for_selected_month_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='omniforecast',
            old_name='ly_com_sales_unit_slected_month_sum',
            new_name='ly_com_sales_unit_selected_month_sum',
        ),
        migrations.RenameField(
            model_name='omniforecast',
            old_name='ly_store_sales_unit_slected_month_sum',
            new_name='ly_store_sales_unit_selected_month_sum',
        ),
        migrations.RenameField(
            model_name='omniforecast',
            old_name='ty_com_sales_unit_slected_month_sum',
            new_name='ty_com_sales_unit_selected_month_sum',
        ),
        migrations.RenameField(
            model_name='omniforecast',
            old_name='ty_store_sales_unit_slected_month_sum',
            new_name='ty_store_sales_unit_selected_month_sum',
        ),
        migrations.RenameField(
            model_name='storeforecast',
            old_name='std_ty_unit_Sales_std',
            new_name='std_ty_unit_sales',
        ),
        migrations.AddField(
            model_name='comforecast',
            name='ly_com_sales_unit_selected_month_sum',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
