# Generated by Django 5.1.5 on 2025-05-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0009_rename_forecasting_method_omniforecast_forecasting_method_com_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=100, verbose_name='Product ID')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note Description')),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True, verbose_name='Assigned To')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['pid'], name='forecast_fo_pid_c00c6a_idx')],
            },
        ),
    ]
