# Generated by Django 5.1.5 on 2025-05-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0009_rename_forecasting_method_omniforecast_forecasting_method_com_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comforecast',
            name='average_store_sale_thru',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comforecast',
            name='macy_SOQ_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comforecast',
            name='qty_added_to_balance_SOQ_forecast_month',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comforecast',
            name='qty_added_to_maintain_OH_forecast_month',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comforecast',
            name='qty_added_to_maintain_OH_next_forecast_month',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='average_store_sale_thru',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='macy_SOQ_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='qty_added_to_balance_SOQ_forecast_month',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='qty_added_to_maintain_OH_forecast_month',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='qty_added_to_maintain_OH_next_forecast_month',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeforecast',
            name='average_store_sale_thru',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeforecast',
            name='macy_SOQ_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeforecast',
            name='qty_added_to_balance_SOQ_forecast_month',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeforecast',
            name='qty_added_to_maintain_OH_forecast_month',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeforecast',
            name='qty_added_to_maintain_OH_next_forecast_month',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
