# Generated by Django 5.1.5 on 2025-05-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0010_forecastnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastnote',
            name='reviewed',
            field=models.BooleanField(default=False, verbose_name='Reviewed'),
        ),
    ]
