# Generated by Django 5.1.5 on 2025-05-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0011_forecastnote_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comforecast',
            name='added_qty_macys_soq',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='comforecast',
            name='fldc',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='comforecast',
            name='forecast_month_planned_oh',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='comforecast',
            name='lead_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='comforecast',
            name='next_forecast_month_planned_oh',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='comforecast',
            name='next_forecast_month_planned_shipment',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='comforecast',
            name='total_added_qty',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='comforecast',
            name='vdf_added_qty',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='monthlyforecast',
            name='apr',
            field=models.FloatField(blank=True, null=True, verbose_name='April'),
        ),
        migrations.AlterField(
            model_name='monthlyforecast',
            name='aug',
            field=models.FloatField(blank=True, null=True, verbose_name='August'),
        ),
        migrations.AlterField(
            model_name='monthlyforecast',
            name='dec',
            field=models.FloatField(blank=True, null=True, verbose_name='December'),
        ),
        migrations.AlterField(
            model_name='monthlyforecast',
            name='feb',
            field=models.FloatField(blank=True, null=True, verbose_name='February'),
        ),
        migrations.AlterField(
            model_name='monthlyforecast',
            name='jan',
            field=models.FloatField(blank=True, null=True, verbose_name='January'),
        ),
        migrations.AlterField(
            model_name='monthlyforecast',
            name='jul',
            field=models.FloatField(blank=True, null=True, verbose_name='July'),
        ),
        migrations.AlterField(
            model_name='monthlyforecast',
            name='jun',
            field=models.FloatField(blank=True, null=True, verbose_name='June'),
        ),
        migrations.AlterField(
            model_name='monthlyforecast',
            name='mar',
            field=models.FloatField(blank=True, null=True, verbose_name='March'),
        ),
        migrations.AlterField(
            model_name='monthlyforecast',
            name='may',
            field=models.FloatField(blank=True, null=True, verbose_name='May'),
        ),
        migrations.AlterField(
            model_name='monthlyforecast',
            name='nov',
            field=models.FloatField(blank=True, null=True, verbose_name='November'),
        ),
        migrations.AlterField(
            model_name='monthlyforecast',
            name='oct',
            field=models.FloatField(blank=True, null=True, verbose_name='October'),
        ),
        migrations.AlterField(
            model_name='monthlyforecast',
            name='sep',
            field=models.FloatField(blank=True, null=True, verbose_name='September'),
        ),
        migrations.AlterField(
            model_name='monthlyforecast',
            name='variable_name',
            field=models.CharField(choices=[('MacysProjectionReciepts', 'Macys Projection Receipts'), ('PlannedEOH', 'Planned EOH'), ('PlannedShipment', 'Planned Shipment'), ('PlannedForecast', 'Planned Forecast'), ('RecommendedForecast', 'Recommended Forecast'), ('ForecastByTrend', 'Forecast By Trend'), ('IndexPercentage', 'Index Percentage'), ('GrossProjection', 'Gross Projection'), ('TY_Unit_Sales', 'This Year Unit Sales'), ('LY_Unit_Sales', 'Last Year Unit Sales'), ('LY_OH_Units', 'Last Year On-Hand Units'), ('TY_OH_Units', 'This Year On-Hand Units'), ('TY_Receipts', 'This Year Receipts'), ('LY_Receipts', 'Last Year Receipts'), ('TY_MCOM_Unit_Sales', 'This Year MCOM Unit Sales'), ('LY_MCOM_Unit_Sales', 'Last Year MCOM Unit Sales'), ('TY_OH_MCOM_Units', 'This Year MCOM On-Hand Units'), ('LY_MCOM_OH_Units', 'Last Year MCOM On-Hand Units'), ('PTD_TY_Sales', 'PTD This Year Sales'), ('LY_PTD_Sales', 'Last Year PTD Sales'), ('MCOM_PTD_TY_Sales', 'MCOM PTD This Year Sales'), ('MCOM_PTD_LY_Sales', 'MCOM PTD Last Year Sales'), ('OO_Total_Units', 'OO Total Units'), ('OO_MCOM_Total_Units', 'OO MCOM Total Units'), ('LY_store_unit_sales', 'LY Store Unit Sales'), ('LY_store_EOM_OH', 'LY Store EOM OH'), ('LY_COM_to_TTL', 'LY COM to TTL Sales'), ('LY_COM_to_TTL_OH', 'LY COM to TTL OH'), ('LY_omni_sell_through', 'LY Omni Sell Through'), ('LY_store_sell_through', 'LY Store Sell Through'), ('LY_omni_turn', 'LY Omni Turn'), ('LY_store_turn', 'LY Store Turn'), ('LY_Omni_AUR_Diff_Own', 'LY Omni AUR Diff Own'), ('TY_store_unit_sales', 'TY Store Unit Sales'), ('TY_store_EOM_OH', 'TY Store EOM OH'), ('TY_COM_to_TTL', 'TY COM to TTL Sales'), ('TY_COM_to_TTL_OH', 'TY COM to TTL OH'), ('TY_Omni_AUR_Diff_Own', 'TY Omni AUR Diff Own'), ('TY_Omni_sell_through', 'TY Omni Sell Through'), ('TY_store_sell_through', 'TY Store Sell Through'), ('TY_omni_turn', 'TY Omni Turn'), ('TY_store_turn', 'TY Store Turn'), ('TY_store_unit_sales_diff', 'TY Store Unit Sales Diff'), ('TY_com_unit_sales_diff', 'TY COM Unit Sales Diff'), ('TY_store_eom_oh_diff', 'TY Store EOM OH Diff')], max_length=50, verbose_name='Variable'),
        ),
        migrations.AlterField(
            model_name='omniforecast',
            name='added_qty_macys_soq',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='omniforecast',
            name='com_fldc',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='omniforecast',
            name='door_count',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='omniforecast',
            name='forecast_month_planned_oh',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='omniforecast',
            name='lead_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='omniforecast',
            name='next_forecast_month_planned_oh',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='omniforecast',
            name='store_fldc',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='com_model',
            field=models.FloatField(blank=True, null=True, verbose_name='Com Model'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='current_door_count',
            field=models.FloatField(blank=True, null=True, verbose_name='Door Count'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='department_id',
            field=models.FloatField(blank=True, null=True, verbose_name='Dpt ID'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='fldc',
            field=models.FloatField(blank=True, null=True, verbose_name='FLDC'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='holiday_build_fc',
            field=models.FloatField(blank=True, null=True, verbose_name='HolidayBuildFC'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='in_transit',
            field=models.FloatField(blank=True, null=True, verbose_name='nav OO'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='item_age',
            field=models.FloatField(blank=True, null=True, verbose_name='Item Age'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='kpi_door_count',
            field=models.FloatField(blank=True, null=True, verbose_name='KPI Door count'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='last_4weeks_shipment',
            field=models.FloatField(blank=True, null=True, verbose_name='Last 3Wks Ships'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='last_store_count',
            field=models.FloatField(blank=True, null=True, verbose_name='Old Door Count'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='lastweek_shipment',
            field=models.FloatField(blank=True, null=True, verbose_name='LW Shipments'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='ma_bin',
            field=models.FloatField(blank=True, null=True, verbose_name='RLJ OH'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='macys_onhand',
            field=models.FloatField(blank=True, null=True, verbose_name='MCYOH Units'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='masterstyle_id',
            field=models.FloatField(blank=True, null=True, verbose_name='MstrSt ID'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='min_order',
            field=models.FloatField(blank=True, null=True, verbose_name='Min Order'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='month_to_date_shipment',
            field=models.FloatField(blank=True, null=True, verbose_name='MTD SHIPMENTS'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='net_projection',
            field=models.FloatField(blank=True, null=True, verbose_name='Net Proj'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='oo',
            field=models.FloatField(blank=True, null=True, verbose_name='OO Units'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='out_of_stock_location',
            field=models.FloatField(blank=True, null=True, verbose_name='OOS Locs'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='planned_weeks_of_stock',
            field=models.FloatField(blank=True, null=True, verbose_name='Wks of Stock OH'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='pool_stock',
            field=models.FloatField(blank=True, null=True, verbose_name='Pool Stock'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='rl_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Proj'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='store_model',
            field=models.FloatField(blank=True, null=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='subclass_id',
            field=models.FloatField(blank=True, null=True, verbose_name='SC ID'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='suspended_location_count',
            field=models.FloatField(blank=True, null=True, verbose_name='Suspended Loc Count'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='unalloc_order',
            field=models.FloatField(blank=True, null=True, verbose_name='Unalloc Orders'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='weeks_of_projection',
            field=models.FloatField(blank=True, null=True, verbose_name='Wks of on Proj'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='wip_quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='WIP'),
        ),
        migrations.AlterField(
            model_name='storeforecast',
            name='added_qty_macys_soq',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='storeforecast',
            name='door_count',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='storeforecast',
            name='fldc',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='storeforecast',
            name='forecast_month_planned_oh',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='storeforecast',
            name='lead_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='storeforecast',
            name='next_forecast_month_planned_oh',
            field=models.FloatField(),
        ),
    ]
