# Generated by Django 5.1.5 on 2025-05-27 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0010_comforecast_average_store_sale_thru_and_more'),
        ('forecast', '0012_alter_comforecast_added_qty_macys_soq_and_more'),
    ]

    operations = [
    ]
