# Generated by Django 5.1.5 on 2025-05-29 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0014_alter_comforecast_next_forecast_month_planned_shipment_and_more'),
        ('forecast', '0014_retailinfo_and_more'),
    ]

    operations = [
    ]
