# Generated by Django 5.1.5 on 2025-05-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0015_merge_20250529_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='comforecast',
            name='STD_index_value_original',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comforecast',
            name='month_12_fc_index_original',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comforecast',
            name='std_trend_original',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='STD_index_value_original',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='month_12_fc_index_original',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='omniforecast',
            name='std_trend_original',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeforecast',
            name='STD_index_value_original',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeforecast',
            name='month_12_fc_index_original',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeforecast',
            name='std_trend_original',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
