# Generated by Django 5.1.5 on 2025-05-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0016_comforecast_std_index_value_original_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Website'),
        ),
    ]
