# Generated by Django 5.1.5 on 2025-05-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0017_productdetail_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='website',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Website'),
        ),
    ]
