# Generated by Django 5.1.5 on 2025-05-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0018_alter_productdetail_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='STD_index_value',
            field=models.JSONField(blank=True, null=True, verbose_name='STD Index Value'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='forecasting_method',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Forecasting Method'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='month_12_fc_index',
            field=models.FloatField(blank=True, null=True, verbose_name='12 Month FC Index'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='rolling_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rolling Method'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='std_trend',
            field=models.FloatField(blank=True, null=True, verbose_name='STD Trend'),
        ),
    ]
