# Generated by Django 5.1.5 on 2025-05-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0019_productdetail_std_index_value_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='forecastnote',
            name='forecast_fo_pid_c00c6a_idx',
        ),
        migrations.RemoveField(
            model_name='forecastnote',
            name='reviewed',
        ),
        migrations.AddField(
            model_name='forecastnote',
            name='status',
            field=models.CharField(blank=True, choices=[('not_reviewed', 'Not reviewed'), ('pending', 'Pending'), ('reviewed', 'Reviewed')], default='pending', max_length=13, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='external_factor',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='external_factor_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='total_added_qty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecastnote',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note Description'),
        ),
        migrations.AlterField(
            model_name='forecastnote',
            name='pid',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Product ID'),
        ),
    ]
