# Generated by Django 5.1.5 on 2025-05-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0020_remove_forecastnote_forecast_fo_pid_c00c6a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastnote',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note Description'),
        ),
    ]
