# Generated by Django 5.1.5 on 2025-05-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0021_alter_forecastnote_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='user_added_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
