# Generated by Django 5.1.5 on 2025-05-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0022_productdetail_user_added_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastnote',
            name='status',
            field=models.CharField(blank=True, choices=[('not_reviewed', 'Not reviewed'), ('pending', 'Pending'), ('reviewed', 'Reviewed')], default='not_reviewed', max_length=13, null=True, verbose_name='Status'),
        ),
    ]
