# Generated by Django 5.1.5 on 2025-05-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0023_alter_forecastnote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
