# Generated by Django 5.1.5 on 2025-06-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0024_productdetail_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastnote',
            name='product_assigned_to',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='product_assigned_to'),
        ),
    ]
