# Generated by Django 5.1.5 on 2025-06-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0025_forecastnote_product_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='week_of_forecast_month',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
