# Generated by Django 5.1.5 on 2025-06-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0026_rename_added_only_to_balance_macys_soq_comforecast_is_inventory_maintained_com_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailinfo',
            name='current_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
