# Generated by Django 5.1.5 on 2025-06-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0027_retailinfo_current_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetupload',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Sheet Name'),
        ),
    ]
