# Generated by Django 5.1.5 on 2025-06-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0028_alter_sheetupload_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetupload',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Sheet Name'),
        ),
    ]
