# Generated by Django 5.1.5 on 2025-06-07 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0030_productdetail_id_alter_productdetail_product_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='forecastnote',
            name='forecast_fo_sheet_i_344a9d_idx',
        ),
        migrations.RemoveIndex(
            model_name='monthlyforecast',
            name='forecast_mo_product_044781_idx',
        ),
        migrations.RenameField(
            model_name='forecastnote',
            old_name='product',
            new_name='productdetail',
        ),
        migrations.RenameField(
            model_name='monthlyforecast',
            old_name='product',
            new_name='productdetail',
        ),
        migrations.AlterUniqueTogether(
            name='monthlyforecast',
            unique_together={('productdetail', 'variable_name', 'year')},
        ),
        migrations.AddIndex(
            model_name='forecastnote',
            index=models.Index(fields=['sheet', 'productdetail'], name='forecast_fo_sheet_i_3bc183_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyforecast',
            index=models.Index(fields=['productdetail', 'variable_name'], name='forecast_mo_product_29e694_idx'),
        ),
    ]
