# Generated by Django 5.1.5 on 2025-06-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0031_remove_forecastnote_forecast_fo_sheet_i_344a9d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='id',
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='product_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Cross Ref'),
        ),
    ]
