# Generated by Django 5.1.5 on 2025-06-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0032_remove_productdetail_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='product_id',
            field=models.CharField(max_length=50, verbose_name='Cross Ref'),
        ),
    ]
