# Generated by Django 5.1.5 on 2025-06-07 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0033_productdetail_id_alter_productdetail_product_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productdetail',
            name='forecast_pr_sheet_i_73a416_idx',
        ),
        migrations.AddIndex(
            model_name='productdetail',
            index=models.Index(fields=['sheet', 'product_id'], name='forecast_pr_sheet_i_a99578_idx'),
        ),
    ]
