openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /api/api/download/:
    get:
      operationId: api_api_download_retrieve
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/sheet/:
    get:
      operationId: api_sheet_retrieve
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/sheet/{sheet_name}/:
    get:
      operationId: api_sheet_retrieve_2
      parameters:
      - in: path
        name: sheet_name
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/upload/:
    post:
      operationId: api_upload_create
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /forecast/api/download/:
    get:
      operationId: forecast_api_download_retrieve
      tags:
      - forecast
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /forecast/api/product/{id}/:
    get:
      operationId: forecast_api_product_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - forecast
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    put:
      operationId: forecast_api_product_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - forecast
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /forecast/upload/:
    post:
      operationId: forecast_upload_create
      tags:
      - forecast
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
