STORE_RENAME_MAP = {
    "category": "Category",
    "pid": "Pid",
    "rlj": "RLJ",
    "country": "Country",
    "lead_time": "Lead time",
    "is_lead_guideline_in_holiday": "Country holiday",
    "current_fc_index": "12 Month FC index",
    "loss_updated": "loss%",
    "new_month_12_fc_index": "12 Month FC index(loss%)",
    "std_index_value": "STD Months",
    "std_trend": "Trend",
    "is_inventory_maintained": "Inventory maintained",
    "trend_index_difference": "Trend Index difference",
    "is_red_box_item": "Red box item",
    "forecasting_method": "Forecasting method",
    "kpi_door_count": "Door Count",
    "average_com_oh": "Average com OH",
    "fldc": "FLDC",
    "birthstone": "Birthstone",
    "birthstone_month": "Birthstone Month",
    "is_considered_birthstone": "Considered Birthstone",
    "forecast_month": "Forecast month",
    "forecast_month_required_quantity": "Forecast month \nRequired quantity",
    "forecast_month_planned_oh_before": "Forecast month\n planned OH \n before adding qty",
    "next_forecast_month": "Next Forecast month",
    "next_forecast_month_required_quantity": "Next forecast month \n Required quantity",
    "next_forecast_month_planned_oh_before": "Next Forecast month \nplanned OH \n before adding qty",
    "forecast_month_planned_shipment": "Forecast month \n planned shipment",
    "next_forecast_month_planned_shipment": "Next Forecast month \nplanned shipment",
    "qty_added_to_maintain_oh_forecast_month": "Forecast month \n Qty Added \n (Maintain Planned OH)",
    "qty_added_to_maintain_oh_next_forecast_month": "Next Forecast month \n Qty Added \n (Maintain Planned OH)",
    "qty_added_to_balance_soq_forecast_month": "Macys SOQ Qty Added",
    "recommended_total_quantity": "Total Added Qty",
    "average_store_sale_thru": "Average Store SellThru",
    "macys_proj_receipt_upto_forecast_month": "Macys SOQ Total",
    "macy_soq_percentage": "Macy SOQ\n percentage% \nneed to given",
    "qty_given_to_macys": "Actual Macy SOQ given",
    "is_below_min_order": "Below min order",
    "is_over_macys_soq": "Over macys SOQ",
    "is_added_only_to_balance_macys_soq": "Added Qty (only Macys SOQ Maintained)",
    "is_need_to_review_first": "Need to review first\n(Below Palnned OH)",
    "valentine_day":"Valentine Day",
    "mothers_day":"Mothers Day",
    "fathers_day":"Fathers Day",
    "womens_day":"Womens Day"
}
COM_RENAME_MAP = {
    "category": "Category",
    "pid": "Pid",
    "rlj": "RLJ",
    "country": "Country",
    "lead_time": "Lead time",
    "is_lead_guideline_in_holiday": "Country holiday",
    "std_index_value": "STD Months",
    "new_month_12_fc_index": "12 Month FC index",
    "final_com_trend": "Trend",
    "std_trend_original": "Adjusted trend",
    "is_com_inventory_maintained": "Inventory maintained",
    "trend_index_difference": "Trend Index difference",
    "is_red_box_item": "Red box item",
    "forecasting_method": "Forecasting method",
    "minimum_required_oh_for_com": "Minimum required oh",
    "fldc": "FLDC",
    "forecast_month": "Forecast month",
    "forecast_month_required_quantity": "Forecast month \nRequired quantity",
    "forecast_month_planned_oh_before": "Forecast month\n planned OH \n before adding qty",
    "next_forecast_month": "Next Forecast month",
    "next_forecast_month_required_quantity": "Next forecast month \n Required quantity",
    "next_forecast_month_planned_oh_before": "Next Forecast month \nplanned OH \n before adding qty",
    "is_vdf_item": "VDF status",
    "vdf_added_quantity": "VDF Qty Added",
    "qty_added_to_maintain_oh_forecast_month": "Forecast month \n Qty Added \n (Maintain Planned OH)",
    "qty_added_to_maintain_oh_next_forecast_month": "Next Forecast month \n Qty Added \n (Maintain Planned OH)",
    "qty_added_to_balance_soq_forecast_month": "Macys SOQ Qty Added",
    "forecast_month_planned_shipment": "Forecast month \n planned shipment",
    "next_forecast_month_planned_shipment": "Next Forecast month \n planned shipment",
    "recommended_total_quantity": "Total added qty",
    "average_store_sale_thru": "Average Store SellThru",
    "macys_proj_receipt_upto_forecast_month": "Macys SOQ Total",
    "macy_soq_percentage": "Macy SOQ\n percentage% \nneed to given",
    "qty_given_to_macys": "Actual Macy SOQ given",
    "is_below_min_order": "Below min order",
    "is_over_macys_soq": "Over macys SOQ",
    "is_added_only_to_balance_macys_soq": "Added Qty (only Macys SOQ Maintained)",
    "is_need_to_review_first": "Need to review first\n(Below Palnned OH)",
    "valentine_day":"Valentine Day",
    "mothers_day":"Mothers Day",
    "fathers_day":"Fathers Day",
    "womens_day":"Womens Day",
}

OMNI_RENAME_MAP = {
    "category": "Category",
    "pid": "Pid",
    "rlj": "RLJ",
    "country": "Country",
    "lead_time": "lead time",
    "is_lead_guideline_in_holiday": "Country holiday",
    "is_red_box_item": "red_box item",
    "std_index_value": "STD Months",
    "com_month_12_fc_index": "12 Month FC index\n Com",
    "com_trend_for_selected_month": "Trend\ncom ",
    "is_com_inventory_maintained": "Inventory maintained\n Com",
    "trend_index_difference_com": "Trend index difference(com)",
    "forecasting_method_for_com": "forecasting_method(com)",
    "minimum_required_oh_for_com": "Minimum required OH",
    "com_fldc": "Com FLDC",
    "forecast_month": "Forecast month",
    "forecast_month_required_quantity_com": "Forecast month \nRequired quantity\n(Com)",
    "next_forecast_month": "Next Forecast Month",
    "next_forecast_month_required_quantity_com": "Next Forecast month \nRequired quantity\n(Com)",
    "store_month_12_fc_index_original": "12 Month FC index\n(Store)",
    "loss_updated": "loss%",
    "store_month_12_fc_index_loss": "12 Month FC index(loss%)\n(Store)",
    "store_trend": "Trend\nStore",
    "is_store_inventory_maintained": "Inventory maintained\n(Store)",
    "trend_index_difference_store": "Trend index difference(store)",
    "forecasting_method_for_store": "Forecasting method(store)",
    "kpi_door_count": "Door Count",
    "store_fldc": "store FLDC",
    "birthstone": "birthstone",
    "birthstone_month": "birthstone month",
    "is_considered_birthstone": "Considered Birthstone",
    "forecast_month_required_quantity_store": "forecast month \n Required quantity(store)",
    "next_forecast_month_required_quantity_store": "Next forecast month \n Required quantity(store)",
    "forecast_month_required_quantity": "Forecast month \n Required quantity(combined)",
    "forecast_month_planned_oh_before": "Forecast month\n planned OH \n before adding qty",
    "next_forecast_month_required_quantity": "Next Forecast month \nRequired quantity(combined)",
    "next_forecast_month_planned_oh_before": "Next Forecast month\n planned OH \n before adding qty",
    "qty_added_to_maintain_oh_forecast_month": "Forecast month \n Qty Added \n (Maintain Planned OH)",
    "qty_added_to_maintain_oh_next_forecast_month": "Next Forecast month \n Qty Added \n (Maintain Planned OH)",
    "qty_added_to_balance_soq_forecast_month": "Macys SOQ Qty Added",
    "forecast_month_planned_shipment": "Forecast month \n planned shipment",
    "next_forecast_month_planned_shipment": "Next Forecast month \n planned shipment",
    "recommended_total_quantity": "Total added qty",
    "average_store_sale_thru": "Average Store SellThru",
    "macys_proj_receipt_upto_forecast_month": "Macys SOQ Total",
    "macy_soq_percentage": "Macy SOQ\n percentage% \nneed to given",
    "qty_given_to_macys": "Actual Macy SOQ given",
    "is_below_min_order": "Below min order",
    "is_over_macys_soq": "Over macys SOQ",
    "is_added_only_to_balance_macys_soq": "Added Qty (only Macys SOQ Maintained)",
    "is_need_to_review_first": "Need to review first\n(Below Palnned OH)",
    "valentine_day":"Valentine Day",
    "mothers_day":"Mothers Day",
    "fathers_day":"Fathers Day",
    "womens_day":"Womens Day",
}

# MONTH_WEEK_DICT = {
# "FEB": feb_weeks,
# "MAR": mar_weeks,
# "APR": apr_weeks,
# "MAY": may_weeks,
# "JUN": jun_weeks,
# "JUL": jul_weeks,
# "AUG": aug_weeks,
# "SEP": sep_weeks,
# "OCT": oct_weeks,
# "NOV": nov_weeks,
# "DEC": dec_weeks,
# "JAN": jan_weeks
# }

ALL_VALUES = [
    "PID/BLU/MKST", "Current FC Index", "(TY/LY) STD Sales Index/12M FC", "STD Trend / 12M FC",
    "Item Status/Forecasting Method/Safe", "Current Str Cnt/Last Str Cnt/Last Updated",
    "Store Model/Com Model/TTL Model", "MA Proj/Proj Ball/Holiday Bd FC",
    "MCY/OH/OH in Transit/MTD Ships/LW Ships", "Planned WOS/WOP/Wkly Avg Sale/Last 4 Wks Ships",
    "Actual WOS/WOP/Real OOS Loc", "Excess Proj Qty & $ / Recall Wks of Poj & Qty",
    "Proj Qty & $ to Release / Note", "Vendor/Min order", "RL TTL/Net Proj/ORD Unalloc/+/− to Model",
    "MA Bin/FLDC/WIP QTY/REPLN HOLD DATE", "WIP Demand", "MD Status/Store & Mcom Repl",
    "TTL Last Repl/Age/Mths Active", "Last Cost/Owned/TKT Ret/GM/Actual GM", "Metal Lock/MFG Policy",
    "KPI DATA", "Last KPI Door count", "Diff to Current Door",
    "Out of Stock Locations", "Suspended Location count",
    "Click to View online", "DEPT #", "Sub Class", "Masterstyle", "PID Desc",
    "COM 1st Live/Live Site/V2C/WebID/STD Rtn", "Web ID Description",
    "Last Reviewed Date/Code/Qty to Enter", "Current Review Comments"
]

MONTHLY_VALUES = ['FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT',
                'NOV', 'DEC', 'JAN', 'ANNUAL', 'SPRING', 'FALL']

MONTH_DATA = [
    ["All", ""],
    ["Feb", 1],
    ["Mar", 2],
    ["Apr", 3],
    ["May", 4],
    ["Jun", 5],
    ["Jul", 6],
    ["Aug", 7],
    ["Sep", 8],
    ["Oct", 9],
    ["Nov", 10],
    ["Dec", 11],
    ["Jan", 12],
]

VDF_ITEMS = [
    "M5616A7PL1WCH",
    "M5616A7PL1PNCH",
    "PA1065P5MDBC0",
    "PA4234P3A7AG0",
    "PA7376P3A7AZ1",
    "SM7452A8FPL3",
    "RH70792PF3W-E",
    "PJ6298P0ZZYE0",
    "RH7079FPF3PNE-M",
    "PA7589P6ZZAZ0",
    "87-H41P",
    "87-G93P",
    "TRP2394Y18",
    "L2469DS1PT.4",
    "TRB048783Y725",
    "TRB073147T775",
    "TRE073035Y",
    "TRE075696Y",
    "TRN068317Y6",
    "TRN068317Y7",
    "TRN070561Y75",
    "40-L23L",
    "FYC078786Y6",
    "40-L22L",
    "40-L29L",
    "40-L21L",
    "40-L18L",
    "TRN068317Y8",
    "CJ1244Z1ZZSG0",
    "DA1504ZZQ9SE0",
    "DA1504ZZQ9SG0",
    "DA1504ZZQ9SI0",
    "DA1504ZZQ9SK0",
    "DA4680ZZA9SG0",
    "DA5133ZZA8YI2",
    "DA5467ZZ19YG0",
    "FRC039354Y75",
    "TRC013552Y75",
    "TRC072852Y85",
    "TRC072860Y75",
    "TRN029005B6",
    "TRN029005B7",
    "TRN029005B8",
    "TRN029005B9",
    "TRN064686Y6",
    "TRN064686Y7",
    "TRN064686Y8",
    "TRN064686Y9",
    "TRN065059B6",
    "TRN065059B7",
    "TRN065059B8",
    "TRN065059B9",
    "TRN069744Y6",
    "TRN069744Y75",
    "TRN069744Y9",
    "83-441",
    "L2470DS1PT.0",
    "TRB067031Y75",
    "TRE079588Y",
    "31-G84",
    "36-T95SKI-MCY",
    "60-F08",
    "260.8R.20",
    "260.8RW.16",
    "260.8RW.18MCY",
    "260.8RW.20",
    "643.030W.18",
    "643.030W.24",
    "643.045PFH.20",
    "TRC039354Y18",
    "FRE013242Y",
    "FRE063670Y20",
    "1FRE021320Y60",
    "FRE023795Y",
    "38-B06",
    "68-285",
    "CA7442S5A8SZ0",
    "CJ4593H9A7YG0",
    "CJ6275H5ZZYG0",
    "SJX13195CEPCW-E",
    "SM17345FOXWSZ-6E",
    "SM17345FOXWSZ-8E",
    "FRN017149Y6",
    "FRN017149Y7"
]
HOLIDAYS_DATA = [
    {'Holiday': 'valentine_day', 'Month': 'Feb', 'Day': 14, 'Week': 2},
    {'Holiday': 'women_day', 'Month': 'Mar', 'Day': 8, 'Week': 2},
    {'Holiday': 'father_day', 'Month': 'Jun', 'Day': 21, 'Week': 3},
    {'Holiday': 'mothers_day', 'Month': 'Nov', 'Day': 10, 'Week': 2}
]

NOT_FORECAST_STATUS = ['VDF/MTO', 'VDF/TBD', 'NGF', 'DNP', 'MD', 'MTC', 'TEST', 'WATCH', 'MAINTAIN', 'DISC', 'nan']

WEEK_TO_ADD_FOR_HOLIDAY = 5 
MONTHS = ['FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC', 'JAN']

SPRING_MONTHS = ['FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL']

FALL_MONTHS = ['AUG', 'SEP', 'OCT', 'NOV', 'DEC', 'JAN']
MONTH_COLUMN_MAP = {
    'FEB': 'I', 'MAR': 'J', 'APR': 'K', 'MAY': 'L', 'JUN': 'M',
    'JUL': 'N', 'AUG': 'O', 'SEP': 'P', 'OCT': 'Q', 'NOV': 'R',
    'DEC': 'S', 'JAN': 'T'
}

VENDOR_DATA = [
            {"Vendor Name": "ALMOND (THAILAND) LIMITED", "Country of Origin": "Thailand", "Lead Time(weeks)": 8},
            {"Vendor Name": "AMMANTE JEWELLS LLP", "Country of Origin": "India", "Lead Time(weeks)": 8},
            {"Vendor Name": "ARIN", "Country of Origin": "Peru", "Lead Time(weeks)": 9},
            {"Vendor Name": "ARPAS INTERNATIONAL LTD", "Country of Origin": "US", "Lead Time(weeks)": 9},
            {"Vendor Name": "ASIAN STAR COMPANY LTD", "Country of Origin": "India", "Lead Time(weeks)": 8},
            {"Vendor Name": "BEAUTY GEMS FACTORY CO LTD", "Country of Origin": "Thailand", "Lead Time(weeks)": 8},
            {"Vendor Name": "CHARM AMERICA", "Country of Origin": "US", "Lead Time(weeks)": 9},
            {"Vendor Name": "CREATIONS JEWELLERY MFG. PVT. LTD.", "Country of Origin": "India", "Lead Time(weeks)": 8},
            {"Vendor Name": "DAISY'S COLLECTION, INC", "Country of Origin": "China", "Lead Time(weeks)": 8},
            {"Vendor Name": "DEORO - WIRE", "Country of Origin": "Peru", "Lead Time(weeks)": 9},
            {"Vendor Name": "DIA GOLD CREATION PVT. LTD.", "Country of Origin": "India", "Lead Time(weeks)": 8},
            {"Vendor Name": "DRL Manufacturing - LG", "Country of Origin": "DRL", "Lead Time(weeks)": 10},
            {"Vendor Name": "DRL MANUFACTURING S.A.", "Country of Origin": "DRL", "Lead Time(weeks)": 10},
            {"Vendor Name": "DRL/SARDELLI", "Country of Origin": "DRL", "Lead Time(weeks)": 10},
            {"Vendor Name": "GDL JEWELLERY LTD", "Country of Origin": "Thailand", "Lead Time(weeks)": 8},
            {"Vendor Name": "GOLDENLINE C/O BOGAZICI HEDIYELIK A.S.", "Country of Origin": "US", "Lead Time(weeks)": 9},
            {"Vendor Name": "IJM-INTERCONTINENTAL JEWELLERY MFG", "Country of Origin": "Thailand", "Lead Time(weeks)": 8},
            {"Vendor Name": "JOHN C NORDT COMPANY", "Country of Origin": "US", "Lead Time(weeks)": 9},
            {"Vendor Name": "LARA CORPORATION LIMITED", "Country of Origin": "China", "Lead Time(weeks)": 8},
            {"Vendor Name": "Leach & Garner (HK) Limited", "Country of Origin": "China", "Lead Time(weeks)": 8},
            {"Vendor Name": "LINEA NUOVA S.A.", "Country of Origin": "Peru", "Lead Time(weeks)": 9},
            {"Vendor Name": "Milor S.P.A", "Country of Origin": "Italy", "Lead Time(weeks)": 9},
            {"Vendor Name": "MIORO GOLD, LLC", "Country of Origin": "US", "Lead Time(weeks)": 9},
            {"Vendor Name": "NEW GOLD", "Country of Origin": "US", "Lead Time(weeks)": 9},
            {"Vendor Name": "PD&P LTD.", "Country of Origin": "China", "Lead Time(weeks)": 8},
            {"Vendor Name": "RICHLINE ITALY SRL", "Country of Origin": "Italy", "Lead Time(weeks)": 12},
            {"Vendor Name": "RICHLINE SA PTY", "Country of Origin": "Zales", "Lead Time(weeks)": None},
            {"Vendor Name": "RLG STANDARD MANUFACTURING VENDOR", "Country of Origin": "US", "Lead Time(weeks)": 9},
            {"Vendor Name": "S&S JEWELRY", "Country of Origin": "US", "Lead Time(weeks)": 9},
            {"Vendor Name": "SABELLI, S.A. DE C.V.", "Country of Origin": "Mexico", "Lead Time(weeks)": 9},
            {"Vendor Name": "SERENITY JEWELS PVT LTD", "Country of Origin": "India", "Lead Time(weeks)": 8},
            {"Vendor Name": "SHANGOLD INDIA LTD", "Country of Origin": "India", "Lead Time(weeks)": 8},
            {"Vendor Name": "SILO SPA-WIRES", "Country of Origin": "Italy", "Lead Time(weeks)": 12},
            {"Vendor Name": "STRONG JEWELRY(HK) CO LTD CHONG", "Country of Origin": "China", "Lead Time(weeks)": 8},
            {"Vendor Name": "T.C.I. LTD", "Country of Origin": "China", "Lead Time(weeks)": 8},
            {"Vendor Name": "National Chain", "Country of Origin": "US", "Lead Time(weeks)": 9},
            {"Vendor Name": "Leach & Garner (HK) Limited", "Country of Origin": "China", "Lead Time(weeks)": 8},
            {"Vendor Name": "LEACH & GARNER(HK) LTD", "Country of Origin": "China", "Lead Time(weeks)": 8},
            {"Vendor Name": "MANJUSAKA JEWELERS CO.,LTD", "Country of Origin": "China", "Lead Time(weeks)": 8},
            {"Vendor Name": "MEICHONG JEWELRY (HK) COMPANY LIMITED", "Country of Origin": "China", "Lead Time(weeks)": 8},
            {"Vendor Name": "NATIONAL CHAIN", "Country of Origin": "US", "Lead Time(weeks)": 9},
            {"Vendor Name": "PRIME DIRECT LIMITED", "Country of Origin": "China", "Lead Time(weeks)": 8},
        ]


BIRTHSTONE_DATA = [
            (1, 'January', 'Garnet'),
            (2, 'February', 'Amethyst'),
            (3, 'March', 'Aquamarine'),
            (4, 'April', 'Diamond'),
            (5, 'May', 'Emerald'),
            (6, 'June', 'Pearl'),
            (7, 'July', 'Ruby'),
            (8, 'August', 'Peridot'),
            (9, 'September', 'Sapphire'),
            (10, 'October', 'Opal'),
            (11, 'November', 'Citrine'),
            (12, 'December', 'Tanzanite')
        ]